<?php
session_start();

// Check if user is logged in and has Admin role
if (!isset($_SESSION['username']) || $_SESSION['role'] !== 'Admin') {
    header("Location: ../admin-login.html");
    exit();
}

// Database connection
$mysqli = new mysqli("localhost", "root", "", "fyp");

// Check connection
if ($mysqli->connect_error) {
    die("Connection failed: " . $mysqli->connect_error);
}

// Get all vehicles
$query = "SELECT * FROM vehicles ORDER BY vehicle_number ASC";
$result = $mysqli->query($query);

if (!$result) {
    die("Query failed: " . $mysqli->error);
}

// Set headers for PDF
header('Content-Type: text/html; charset=utf-8');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vehicles Report - <?php echo date('Y-m-d'); ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background: #fff;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #5c1f00;
        }
        .logo {
            max-width: 120px;
            margin-bottom: 15px;
        }
        .report-title {
            color: #5c1f00;
            font-size: 24px;
            margin: 10px 0;
        }
        .report-info {
            font-size: 14px;
            color: #666;
            margin: 10px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 12px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        th {
            background: #5c1f00;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #5c1f00;
            font-size: 12px;
            color: #666;
        }
        .expiry-warning {
            color: #dc3545;
            font-weight: 500;
        }
        .expiry-soon {
            color: #ffc107;
            font-weight: 500;
        }
        @media print {
            body {
                padding: 0;
            }
            .print-button {
                display: none;
            }
        }
        .print-button {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 10px 20px;
            background: #5c1f00;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <button class="print-button" onclick="window.print()">
        <i class="fas fa-print"></i> Print Report
    </button>

    <div class="header">
        <img src="../img/logo.png" alt="SILO Logo" class="logo">
        <h1 class="report-title">Vehicles Report</h1>
        <div class="report-info">
            Generated on: <?php echo date('Y-m-d H:i:s'); ?><br>
            Generated by: <?php echo htmlspecialchars($_SESSION['username']); ?>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Vehicle Number</th>
                <th>Description</th>
                <th>Insurance Expiry</th>
                <th>Road Tax Expiry</th>
                <th>GPS</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            while($row = $result->fetch_assoc()): 
                $today = new DateTime();
                $insurance_expiry = new DateTime($row['insurance_expiry']);
                $roadtax_expiry = new DateTime($row['roadtax_expiry']);
                
                $insurance_diff = $today->diff($insurance_expiry)->days;
                $roadtax_diff = $today->diff($roadtax_expiry)->days;
            ?>
                <tr>
                    <td><?php echo htmlspecialchars($row['vehicle_number']); ?></td>
                    <td><?php echo htmlspecialchars($row['description']); ?></td>
                    <td class="<?php echo ($insurance_diff < 30) ? ($insurance_diff < 7 ? 'expiry-warning' : 'expiry-soon') : ''; ?>">
                        <?php echo date('d/m/Y', strtotime($row['insurance_expiry'])); ?>
                    </td>
                    <td class="<?php echo ($roadtax_diff < 30) ? ($roadtax_diff < 7 ? 'expiry-warning' : 'expiry-soon') : ''; ?>">
                        <?php echo date('d/m/Y', strtotime($row['roadtax_expiry'])); ?>
                    </td>
                    <td><?php echo htmlspecialchars($row['gps'] ?: '-'); ?></td>
                    <td><?php echo htmlspecialchars($row['remarks'] ?: '-'); ?></td>
                </tr>
            <?php endwhile; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>© <?php echo date('Y'); ?> SILO (M) Sdn. Bhd. All Rights Reserved</p>
        <p>This report is system generated. For any queries, please contact the administrator.</p>
    </div>

    <script>
        window.onload = function() {
            setTimeout(function() {
                window.print();
            }, 1000);
        };
    </script>
</body>
</html>
<?php $mysqli->close(); ?> 