<?php
session_start();

// Check if user is logged in and has Admin role
if (!isset($_SESSION['username']) || $_SESSION['role'] !== 'Admin') {
    header("Location: ../admin-login.html");
    exit();
}

// Database connection
$mysqli = new mysqli("localhost", "root", "", "fyp");

// Check connection
if ($mysqli->connect_error) {
    die("Connection failed: " . $mysqli->connect_error);
}

// Fetch supplier data
$query = "SELECT 
            vehicle_number,
            roadtax_expiry,
            description,
            gps,
            remarks
            FROM vehicles
            ORDER BY vehicle_number ASC";

$result = $mysqli->query($query);

if (!$result) {
    die("Query failed: " . $mysqli->error);
}

// Store data in an array for reuse
$suppliers = [];
while ($row = $result->fetch_assoc()) {
    $suppliers[] = $row;
}

// Check if the user requested CSV export
if (isset($_GET['export']) && $_GET['export'] === 'csv') {
    // Set headers for Excel export
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="Suppliers_Report_' . date('Y-m-d') . '.csv"');
    header('Cache-Control: max-age=0');

    // Output column headers
    echo "Company Name,Contact Person,Email,Phone,Address,City,Postcode\n";

    // Output rows
    foreach ($suppliers as $row) {
        echo implode(",", [
            $row['vehicle_number'],
            $row['insurance_expiry'],
            $row['roadtax_expiry'],
            $row['description'],
            $row['gps'],
            $row['remarks']
        ]) . "\n";
    }

    // Close database connection
    $mysqli->close();
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Suppliers Report - <?php echo date('Y-m-d'); ?></title>
    <style>
        /* Styling */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background: #fff;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #5c1f00;
        }
        .logo {
            max-width: 120px;
            margin-bottom: 15px;
        }
        .report-title {
            color: #5c1f00;
            font-size: 24px;
            margin: 10px 0;
        }
        .report-info {
            display: flex;
            justify-content: space-between;
            margin: 20px 0;
            font-size: 15px;
            color: #666;
        }
        .download-button {
            padding: 10px 20px;
            background: #5c1f00;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #5c1f00;
            font-size: 15px;
            color: #666;
            page-break-inside: avoid;
        }
        .download-button {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 10px 20px;
            background: #5c1f00;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
            z-index: 1000;
        }
    </style>
</head>
<body>

<div class="header">
<img src="../img/logo.png" alt="SILO Logo" class="logo">
<h1 class="report-title">Supplier Excel Report</h1>
        <div class="report-info">
    <p>Generated by: <?php echo htmlspecialchars($_SESSION['username']); ?></p>
    <p>Date: <?php echo date('Y-m-d H:i:s'); ?></p>
</div>
    </div>
    <h2>Supplier Excel Report</h2>
<table>
    <thead>
        <tr>
            <th>Company Name</th>
            <th>Contact Person</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
            <th>City</th>
            <th>Postcode</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($suppliers as $row): ?>
            <tr>
                    <td><?php echo htmlspecialchars($row['vehicle_number']); ?></td>
                    <td><?php echo htmlspecialchars($row['description']); ?></td>
                    <td class="<?php echo ($insurance_diff < 30) ? ($insurance_diff < 7 ? 'expiry-warning' : 'expiry-soon') : ''; ?>">
                        <?php echo date('d/m/Y', strtotime($row['insurance_expiry'])); ?>
                    </td>
                    <td class="<?php echo ($roadtax_diff < 30) ? ($roadtax_diff < 7 ? 'expiry-warning' : 'expiry-soon') : ''; ?>">
                        <?php echo date('d/m/Y', strtotime($row['roadtax_expiry'])); ?>
                    </td>
                    <td><?php echo htmlspecialchars($row['gps'] ?: '-'); ?></td>
                    <td><?php echo htmlspecialchars($row['remarks'] ?: '-'); ?></td>
                </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<form action="" method="get">
    <button class="download-button" type="submit" name="export" value="csv">Export to CSV</button>
</form>

<div class="footer">
    <p>© <?php echo date('Y'); ?> SILO (M) Sdn. Bhd. All Rights Reserved</p>
    <p>This report is system generated. For any queries, please contact the administrator.</p>
</div>

</body>
</html>

<?php
// Close database connection
$mysqli->close();
?>
